name: Build And Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "iOS Test"
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with: 
        xcode-version: latest-stable
    - name: Show Xcode Version
      run: xcodebuild -version   
    - name: Install xcpretty
      run: gem install xcpretty    
    - name: Cache SPM
      uses: actions/cache@v2
      with:
        path: SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Unit Test
      run: |
        xcodebuild \
        -project ToiletMap.xcodeproj \
        -scheme ToiletMap-DEVELOP \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 12' \
        -configuration Develop \
        -clonedSourcePackagesDirPath SourcePackages \
        clean test | xcpretty

